# Generated by Django 5.2.1 on 2025-05-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekycdata',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
