# Generated by Django 5.2.1 on 2025-05-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_v2', '0002_alter_ekycdata_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekycdata',
            name='fraud_score',
            field=models.FloatField(default=0.0),
        ),
    ]
